### ISSUE TITLE
Using the fork method to create more than one library projects

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-library-template-ant#2]
I realized one potential issue with the Github method to create new library projects, which consists in forking the processing-library-template repo. 

I applied this method once to create a new library called planetarium (https://github.com/codeanticode/planetarium), and everything went fine. Now I'd like to start a new library, but when I click the Fork button in the processing-library-template page, it takes me to the planetarium repo, instead of allowing me to start with a new one from scratch.

**Comment by Manindra29** [comment]
This is a GitHub limitation. A user can have only one fork of a repo.

There are workarounds though - http://adrianshort.org/2011/11/08/create-multiple-forks-of-a-github-repo/

**Comment by codeanticode** [comment]
cool, thanks for the link. I think it should be added to the project's readme.

**Comment by codeanticode** [comment]
a quick note about the notes from the link, the step where the author sets the empty new repo as the origin:

git remote add git@github.com:adrianshort/ggw.git origin

didn't work as expected for me, and I had to change it as:

git remote add origin https://github.com/adrianshort/ggw.git

(following the naming conventions in that post).

**Comment by prisonerjohn** [comment]
Thanks for the heads up and the link, I'll make sure to add them to the README.
